# Generated by Django 5.1.2 on 2024-11-29 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Name", max_length=100)),
                (
                    "email",
                    models.EmailField(
                        default="example@example.com", max_length=254, unique=True
                    ),
                ),
                ("phone", models.CharField(default="000-000-0000", max_length=15)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("height", models.FloatField(max_length=100)),
                ("weight", models.FloatField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatars/default-avatar.png",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "force",
                    models.CharField(
                        choices=[
                            ("push", "Push"),
                            ("pull", "Pull"),
                            ("static", "Static"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "mechanic",
                    models.CharField(
                        choices=[("compound", "Compound"), ("isolation", "Isolation")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("body only", "Body Only"),
                            ("machine", "Machine"),
                            ("kettlebells", "Kettlebells"),
                            ("dumbbell", "Dumbbell"),
                            ("cable", "Cable"),
                            ("barbell", "Barbell"),
                            ("bands", "Bands"),
                            ("medicine ball", "Medicine Ball"),
                            ("exercise ball", "Exercise Ball"),
                            ("e-z curl bar", "E-Z Curl Bar"),
                            ("foam roll", "Foam Roll"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "instructions",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("stretching", "Stretching"),
                            ("plyometrics", "Plyometrics"),
                            ("strongman", "Strongman"),
                            ("powerlifting", "Powerlifting"),
                            ("cardio", "Cardio"),
                            ("olympic weightlifting", "Olympic Weightlifting"),
                            ("crossfit", "Crossfit"),
                            ("weighted bodyweight", "Weighted Bodyweight"),
                            ("assisted bodyweight", "Assisted Bodyweight"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "primaryMuscles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="primary_muscles",
                        to="FitOn.musclegroup",
                    ),
                ),
                (
                    "secondaryMuscles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_muscles",
                        to="FitOn.musclegroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordResetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_request_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
