# Generated by Django 5.1.3 on 2024-12-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FitOn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChatMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=200, verbose_name="group name"
                    ),
                ),
                ("uid", models.CharField(max_length=80, verbose_name="userid")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "uid"), name="unique_group_chat_member"
                    )
                ],
            },
        ),
    ]
