# Generated by Django 5.1.3 on 2024-12-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FitOn", "0003_alter_groupchatmember_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchatmember",
            name="uid",
            field=models.CharField(max_length=36, verbose_name="userid"),
        ),
    ]
